server:
  port: 3000
  basePath: ''
application:
  domain: pentest.hub
  name: 'PENTEST HUB'
  logo: pentest-hub.png
  favicon: favicon_js.ico
  theme: blue-lightblue # Options: bluegrey-lightgreen blue-lightblue deeppurple-amber indigo-pink pink-bluegrey purple-green deeporange-indigo
  showVersionNumber: false
  showGitHubLinks: false
  localBackupEnabled: true
  numberOfRandomFakeUsers: 0
  altcoinName: Juicycoin
  privacyContactEmail: donotreply@pentest.hub
  customMetricsPrefix: pentesthub
  chatBot:
    name: 'Anonymous'
    greeting: "Nice to meet you <customer-name>, I'm <bot-name>"
    trainingData: 'botDefaultTrainingData.json'
    defaultResponse: "Sorry I couldn't understand what you were trying to say"
    avatar: 'JuicyChatBot.png'
  recyclePage:
    topProductImage: fruit_press.jpg
    bottomProductImage: apple_pressings.jpg
  welcomeBanner:
    showOnFirstStart: true
    title: 'Welcome to PENTEST HUB!'
    message: "<p>Being a web application with a vast number of intended security vulnerabilities, the <strong>PENTEST HUB</strong> is supposed to be the opposite of a best practice or template application for web developers: It is an awareness, training, demonstration and exercise tool for security risks in modern web applications.</h1>"
  cookieConsent:
    backgroundColor: '#2F4F4F'
    textColor: '#ffffff'
    buttonColor: '#558b2f'
    buttonTextColor: '#ffffff'
    message: 'This website uses fruit cookies to ensure you get the juiciest tracking experience.'
    dismissText: 'Me want it!'
    linkText: 'But me wait!'
    linkUrl: 'https://www.youtube.com/watch?v=9PnbKL3wuH4'
  securityTxt:
    contact: 'mailto:donotreply@pentest.hub'
    encryption: 'https://keybase.io/bkimminich/pgp_keys.asc?fingerprint=19c01cb7157e4645e9e2c863062a85a8cbfbdcda'
    acknowledgements: '/#/score-board'
    hiring: '/#/jobs'
  promotion:
    video: owasp_promo.mp4
    subtitles: owasp_promo.vtt
  easterEggPlanet:
    name: Orangeuze
    overlayMap: orangemap2k.jpg
  googleOauth:
    clientId: '1005568560502-6hm16lef8oh46hr2d98vf2ohlnj4nfhq.apps.googleusercontent.com'
    authorizedRedirects:
      - { uri: 'https://demo.owasp-juice.shop' }
      - { uri: 'https://juice-shop.herokuapp.com' }
      - { uri: 'https://preview.owasp-juice.shop' }
      - { uri: 'https://juice-shop-staging.herokuapp.com' }
      - { uri: 'https://juice-shop.wtf' }
      - { uri: 'http://localhost:3000', proxy: 'https://local3000.owasp-juice.shop' }
      - { uri: 'http://127.0.0.1:3000', proxy: 'https://local3000.owasp-juice.shop' }
      - { uri: 'http://localhost:4200', proxy: 'https://local4200.owasp-juice.shop' }
      - { uri: 'http://127.0.0.1:4200', proxy: 'https://local4200.owasp-juice.shop' }
      - { uri: 'http://192.168.99.100:3000', proxy: 'https://localmac.owasp-juice.shop' }
      - { uri: 'http://192.168.99.100:4200', proxy: 'https://localmac.owasp-juice.shop' }
      - { uri: 'http://penguin.termina.linux.test:3000', proxy: 'https://localchromeos.owasp-juice.shop' }
      - { uri: 'http://penguin.termina.linux.test:4200', proxy: 'https://localchromeos.owasp-juice.shop' }
challenges:
  showSolvedNotifications: true
  showHints: false
  showMitigations: true
  codingChallengesEnabled: solved # Options: never  solved  always
  restrictToTutorialsFirst: false 
  overwriteUrlForProductTamperingChallenge: 'https://owasp.slack.com'
  xssBonusPayload: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/228839095&color=%23ff5500&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
  safetyOverride: false
  showFeedbackButtons: true
hackingInstructor:
  isEnabled: false
  avatarImage: JuicyBot.png
  hintPlaybackSpeed: normal # Options: faster fast normal slow slower
products:
  -
    name: 'LAN Turtle'
    price: 8.99
    deluxePrice: 3.99
    limitPerUser: 5
    description: 'The all-time classic.'
    image: lan_turtle.jpg
    reviews:
      - { text: 'One of my favorites!', author: admin }
  -
    name: 'Exam Voucher'
    description: 'You need it!.'
    price: 99.99
    image: exam.jpg
    reviews:
      - { text: 'I bought it for me and my friend.', author: admin }
  -
    name: 'Burp Suite Professional'
    description: 'Must have for pentester.'
    price: 79.99
    image: burp_suite.jpg
  -
    name: 'Ubertooth One'
    description: 'Ubertooth One is an open source 2.4 GHz wireless development platform suitable for Bluetooth experimentation.'
    price: 6.99
    deluxePrice: 2.99
    limitPerUser: 5
    image: ubertooth.jpg
  -
    name: 'Bash Bunny'
    description: 'The groundbreaking payload platform that introduced multi-vector USB attacks has evolved.'
    price: 119.99
    image: bashbunny.jpg
    reviews:
      - { text: 'Like it.', author: bender }
  -
    name: 'Hacker iPhone case'
    description: 'Real fans wear it 24/7!'
    price: 22.49
    limitPerUser: 5
    image: case.jpg
  -
    name: 'PenTest Girlie-Shirt'
    description: 'For serious Capture-the-Flag heroines only!'
    price: 22.49
    image: grl_tshirt.jpg
  -
    name: 'USB Rubber Ducky'
    description: 'USB Rubber ducky is an HID device that looks similar to a USB Pen drive.'
    price: 79.99
    image: ducky.jpg
    urlForProductTamperingChallenge: 'https://shop.hak5.org/products/usb-rubber-ducky'
  -
    name: 'Christmas Super-Surprise-Box (2014 Edition)'
    description: 'Contains a random selection of 10 bottles (each 500ml) of our tastiest juices and an extra fan shirt for an unbeatable price!'
    price: 29.99
    image: undefined.jpg
    useForChristmasSpecialChallenge: true
  -
    name: 'Rippertuer Special Juice'
    description: 'Contains a magical collection of the rarest fruits gathered from all around the world, like Cherymoya Annona cherimola, Jabuticaba Myrciaria cauliflora, Bael Aegle marmelos... and others, at an unbelievable price! <br/><span style="color:red;">This item has been made unavailable because of lack of safety standards.</span>'
    price: 16.99
    image: undefined.jpg
    keywordsForPastebinDataLeakChallenge:
      - hueteroneel
      - eurogium edule
  -
    name: 'Hacker Inside Sticker'
    description: 'Die-cut sticker with the official 2015/2016 logo. By now this is a rare collectors item. <em>Out of stock!</em>'
    price: 99.99
    image: sticker.png
    deletedDate: '2017-04-28'
  -
    name: 'Hacker magnet (16pcs)'
    description: 'For real hackers!'
    price: 1.99
    image: magnet.jpg
  -
    name: 'Hacker Pillow'
    description: 'Hackers also need to sleep! This pillow for you!'
    price: 15.99
    image: pillow.jpg
  -
    name: 'PenTest Sticker Page'
    description: 'Amazing sticker pack!'
    price: 9.99
    image: sticker_page.jpg
  -
    name: 'PenTest Sticker Single'
    description: 'The ultimate laptop decal!'
    price: 4.99
    image: sticker_single.jpg
  -
    name: 'Hacker Cap'
    description: 'This one has got a low profile with an adjustable strap and curved visor.'
    price: 14.99
    image: cap.jpg
    reviews:
      - { text: 'Cool!', author: rapper }
  -
    name: 'Hacker Mug'
    description: 'Black mug with regular logo on one side! Your colleagues will envy you!'
    price: 21.99
    image: fan_mug.jpg
  -
    name: 'Hacker Hoodie'
    description: 'Mr. Robot-style apparel. But in black. And with logo.'
    price: 49.99
    image: fan_hoodie.jpg
  -
    name: 'Hacker Velcro Patch'
    description: '4x3.5" embroidered patch with velcro backside. The ultimate decal for every tactical bag or backpack!'
    price: 2.92
    quantity: 5
    limitPerUser: 5
    image: velcro-patch.jpg
    reviews:
      - { text: 'This thang would look phat on Bobby''s jacked fur coat!', author: rapper }
      - { text: 'Looks so much better on my uniform than the boring Starfleet symbol.', author: jim }
  -
    name: 'Raspberry Pi 4B'
    description: 'Your tiny, dual-display, desktop computer Öand robot brains, smart home hub, media centre, networked AI core, factory controller, and much more'
    price: 79.99
    image: raspberry.jpg
  -
    name: 'Wi-Fi Pineapple'
    description: 'A Wi-Fi Pineapple is a wireless auditing platform from Hak5 that allows network security administrators to conduct penetration tests.'
    price: 109.99
    image: wifi_pineapple.jpg
    reviews:
      - { text: 'I bought it for my hacking team.', author: jim }
  -
    name: 'The Web Application Hacker Handbook'
    description: 'It is never too late to learn!'
    price: 3.99
    image: book.jpg
  -
    name: 'HackRF One'
    description: 'HackRF One from Great Scott Gadgets is a Software Defined Radio peripheral capable of transmission or reception of radio signals from 1 MHz to 6 GHz.'
    price: 67.99
    limitPerUser: 5
    image: hackrf.jpg
  -
    name: 'Proxmark3 RDV4 Kit'
    description: 'The Proxmark 3 is the ultimate RFID platform for pentesters and researchers.'
    price: 489.99
    image: proxmark3.jpg
  -
    name: 'Hacker Shopping Bag'
    description: 'This rare item was designed and handcrafted in Sweden. This is why it is so incredibly expensive despite its complete lack of purpose.'
    price: 99.99
    image: bag.jpg # Exif metadata contains "OpenSCAD" as subtle hint...
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type
    exifForBlueprintChallenge:
      - OpenSCAD
  -
    name: 'Juice Shop Artwork'
    description: 'Unique masterpiece painted with different kinds of juice on 90g/m¬≤ lined paper.'
    price: 278.74
    quantity: 0
    image: artwork.jpg
    deletedDate: '2020-12-24'
  -
    name: 'Acunetix Pro Packet'
    description: 'Sweet & tasty!'
    price: 3.99
    image: acunetix.jpeg
  -
    name: 'Hacking with Python Book'
    description: '<em>The official Companion Guide</em> by Bj√∂rn Kimminich available <a href="https://leanpub.com/juice-shop">for free on LeanPub</a> and also <a href="https://pwning.owasp-juice.shop">readable online</a>!'
    price: 5.99
    image: hack_python_book.jpg
    reviews:
      - { text: 'Even more interesting than watching Interdimensional Cable!', author: morty }
  -
    name: 'Sticker Pack'
    description: 'New!'
    price: 29.99
    quantity: 3
    limitPerUser: 1
    image: stickerpack.jpeg
  -
    name: 'Hacker Coaster'
    description: 'Our coasters are printed in full color and made from thick, premium coaster board.'
    price: 19.99
    quantity: 0
    image: coaster.jpg
  -
    name: 'Hack my password Board Game'
    description: 'This amazing web application security awareness board game is available now!'
    price: 20.01
    quantity: 8
    image: boardgamehackpwd.jpg
    reviews:
      - { text: 'Wait for a 10$ Steam sale of Tabletop Simulator!', author: bjoernOwasp }
  -
    name: 'Hacker Board Game'
    description: 'This amazing web app security awareness board game is available now!'
    price: 20.01
    quantity: 0
    image: boardgame.jpg
    reviews:
      - { text: "Here yo' learn how tha fuck ta not show yo' goddamn phone on camera!", author: rapper }
  -
    name: 'Hack Sticker'
    description: "Die-cut holographic sticker. Stand out from those 08/15-sticker-covered laptops with this shiny beacon of 80's coolness!"
    price: 2.00
    quantity: 0
    image: holo_sticker.png
    reviews:
      - { text: "Rad, dude!", author: rapper }
      - { text: "Looks spacy on Bones' new tricorder!", author: jim }
      - { text: "Will put one on the Planet Express ship's bumper!", author: bender }
  -
    name: 'Hacker Facemask'
    description: "Facemask with compartment for filter from 50% cotton and 50% polyester."
    price: 13.49
    quantity: 0
    limitPerUser: 1
    image: fan_facemask.jpg
    reviews:
      - { text: "K33p5 y0ur ju1cy 5plu773r 70 y0ur53lf!", author: uvogin }
      - { text: "Puny mask for puny human weaklings!", author: bender }
  -
    name: 'ALFA Network'
    description: 'Superior Wi-Fi Performance. Equipped with lastest 802.11ac wireless standards, and years of field-proven experiences, ALFA AWUS036AC provides 2.4GHz 300Mbps or 5GHz 867Mbps Wi-Fi data transfer speeds for outstanding peformance.'
    price: 19.99
    quantity: 1
    limitPerUser: 1
    image: alfa.jpg
    reviews:
      - { text: "üßä Let it go, let it go üé∂ Can't hold it back anymore üé∂ Let it go, let it go üé∂ Turn away and slam the door ‚ùÑÔ∏è", author: rapper }
  -
    name: 'Hacker T-Shirt'
    description: 'Be like true hacker!'
    price: 5000
    quantity: 1
    image: tshirt.jpg
    reviews:
      - { text: "I'd stand on my head to make you a deal for this piece of art.", author: stan }
      - { text: "Just when my opinion of humans couldn't get any lower, along comes Stan...", author: bender }
  -
    name: 'Hacker NotePad'
    description: 'All need it!'
    price: 1000
    quantity: 3
    limitPerUser: 1
    image: notepad.jpg
    reviews:
      - { text: 'DO NOT PLAY WITH THIS! Double-sleeve, then put it in the GitHub Arctic Vault for perfect preservation and boost of secondary market value!', author: accountant }
  -
    name: '20th Anniversary Celebration Ticket'
    description: 'Get your <a href="https://20thanniversary.owasp.org/" target="_blank">free üé´ for OWASP 20th Anniversary Celebration</a> online conference! Hear from world renowned keynotes and special speakers, network with your peers and interact with our event sponsors. With an anticipated 10k+ attendees from around the world, you will not want to miss this live on-line event!'
    price: 0.00000000000000000001
    deletedDate: '2021-09-25'
    limitPerUser: 1
    image: 20th.jpeg
    reviews:
      - { text: "I'll be there! Will you, too?", author: bjoernOwasp }
memories:
  -
    image: 'magn(et)ificent!-1571814229653.jpg'
    caption: 'Magn(et)ificent!'
    user: bjoernGoogle
  -
    image: 'my-rare-collectors-item!-[Ã≤ÃÖ$Ã≤ÃÖ(Ã≤ÃÖ-Õ°¬∞-Õú ñ-Õ°¬∞Ã≤ÃÖ)Ã≤ÃÖ$Ã≤ÃÖ]-1572603645543.jpg'
    caption: 'My rare collectors item! [Ã≤ÃÖ$Ã≤ÃÖ(Ã≤ÃÖ Õ°¬∞ Õú ñ Õ°¬∞Ã≤ÃÖ)Ã≤ÃÖ$Ã≤ÃÖ]'
    user: bjoernGoogle
  -
    image: 'favorite-hiking-place.png'
    caption: 'I love going hiking here...'
    geoStalkingMetaSecurityQuestion: 14
    geoStalkingMetaSecurityAnswer: 'Daniel Boone National Forest'
  -
    image: 'IMG_4253.jpg'
    caption: 'My old workplace...'
    geoStalkingVisualSecurityQuestion: 10
    geoStalkingVisualSecurityAnswer: 'ITsec'
ctf:
  showFlagsInNotifications: false
  showCountryDetailsInNotifications: none # Options: none  name  flag  both
  countryMapping: ~

